# fly.toml app configuration file generated for text-insight-api on 2025-08-26T10:10:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'text-insight-api'
primary_region = 'cdg'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy --schema ./dist/prisma/schema.prisma'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.machines]
    size = "shared-cpu-1x"
    memory_mb = 256

[[vm]]
  size = 'shared-cpu-1x'
    memory_mb = 512
