# fly.toml app configuration file generated for text-insight-api on 2025-08-26T10:10:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'text-insight-api'
primary_region = 'cdg'

[build]   
[
build.args
]
 NODE_ENV = "development" 

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
